.gitignore, README.md, applier/inventory/group_vars/all.yml, applier/inventory/hosts, applier/params/community-ninja-board-deployment, applier/params/community-ninja-board-project, applier/templates/community-ninja-board-build.yml, applier/templates/community-ninja-board-deployment.yml, requirements.yml
Support for OpenShift applier to deploy the application. Instructions in the README
=> Added support for OpenShift applier deployment

src/main/java/com/redhat/sso/ninja/ChartsController.java, src/main/java/com/redhat/sso/ninja/Database2.java, src/main/java/com/redhat/sso/ninja/ManagementController.java
found a race condition where the database was overwritten while it was being used elsewhere creating an inconsistent database
=> removing any re-loading of the database

pom.xml, src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/java/com/redhat/sso/ninja/InitServlet.java, src/main/java/com/redhat/sso/ninja/ManagementController.java, src/main/resources/config.json
especially since we have notifications I'd like to be able to control the time so we don't send notifications at inconvenient hours. Also it helps to be in control of when the scripts run for testing/api limit purposes
=> integration scripts execute at a specific time of day

pom.xml, src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/java/com/redhat/sso/ninja/InitServlet.java, src/main/java/com/redhat/sso/ninja/ManagementController.java, src/main/resources/config.json
updated the google chat url so devs dont accidentally post to a live channel.
=> Chat notification url update

src/main/webapp/events.jsp, src/main/webapp/scorecards.jsp
=> Update to export feature to fix defect where export button prevents

pom.xml
Minor POM updates - enforcing JDK 1.8, Maven 3.0.5.
=> source level 1.8, enforcing maven 3.0.5.

src/main/java/com/redhat/sso/ninja/ChatNotification.java, src/main/java/com/redhat/sso/ninja/Config.java, src/main/java/com/redhat/sso/ninja/ExportController.java, src/main/java/com/redhat/sso/ninja/GoogleDrive2.java, src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/java/com/redhat/sso/ninja/ManagementController.java, src/main/resources/config.json, src/main/webapp/css/style2.css, src/main/webapp/mojo-dashboard-card.jsp, src/main/webapp/mojo-ninjaWall.jsp, src/main/webapp/mojo-raceToBlack-vertical.jsp, src/main/webapp/scorecards.jsp
there's more commits than there should be but the code changes all need to go in, whether they were css tweaks or export re-ordering. I did try rebasing but it said there were no changed to merge, so maybe it's right?
=> change to allow notifications to be sent to different google chat channels

src/main/java/com/redhat/sso/ninja/Database2.java, src/main/java/com/redhat/sso/ninja/ManagementController.java
…I missed somewhere previously that was still hard-coded to 1000
=> making max event entries a configurable value

src/main/webapp/mojo-dashboard-card.jsp
defect on mojo card page for admin users only
=> fixing defect where when loading users card data doesnt update screen

src/main/java/com/redhat/sso/ninja/Config.java, src/main/java/com/redhat/sso/ninja/ManagementController.java, src/main/java/com/redhat/sso/ninja/SupportController.java, src/main/webapp/mojo-dashboard-card.jsp, src/main/webapp/support-trello-all.jsp, src/main/webapp/support-trello-card.jsp
…it's a signed exchange and fails with the "ERR_INVALID_SIGNED_EXCHANGE" error message when calling the scorecard(s) api
=> Multiple changes - Chrome "SIGNED"EXCHANGE" error, Support Initiatives onboarding & a minor support page enhancement

src/main/java/com/redhat/sso/ninja/ChatNotification.java, src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/resources/config.json
added OnError notifications to google chat for script failures, so we know proactively when scripts fail
=> Google Chat notification on script error

ninja-react/src/App.js, ninja-react/src/assets/css/admin.css, ninja-react/src/components/AdminConfigurable.jsx
=> Added AdminConfigurable component (for config and database pages)

ninja-react/.openshift/templates/ninja-board-front-end.yml, ninja-react/Jenkinsfile
This pr contains an openshift template to create build/deploy resources for the front-end app. It also contains a Jenkinsfile for the front-end.
=> Front-End Template Build/Deploy

quarkus/README.MD, quarkus/all-service/pom.xml, quarkus/all-service/src/main/resources/META-INF/openapi.yaml, quarkus/all-service/src/main/resources/application.properties, quarkus/user-service/src/main/java/com/redhat/services/ninja/controller/UserResource.java, quarkus/user-service/src/test/java/com/redhat/services/ninja/controller/UserResourceTest.java
/openapi offers the open api documentation
=> Backend Quarkus OpenAPI: Enabling Quarkus OpenAPI

quarkus/README.MD
The readme documentation now has a section describing the project structure.
=> Backend Quarkus Doc: Adding Structure to README.MD

quarkus/all-service/src/main/resources/META-INF/openapi.yaml, quarkus/all-service/src/main/resources/application.properties, quarkus/all-service/src/test/resources/application.properties, quarkus/data-client/src/main/java/com/redhat/services/ninja/client/LevelClient.java, quarkus/data-service/src/main/java/com/redhat/services/ninja/data/controller/AbstractIdentifiableResource.java, quarkus/data-service/src/main/java/com/redhat/services/ninja/data/controller/LevelResource.java, quarkus/data-service/src/main/java/com/redhat/services/ninja/data/operation/IdentifiableDatabaseOperations.java, quarkus/data-service/src/main/java/com/redhat/services/ninja/data/service/DatabaseEngine.java, quarkus/data-service/src/main/java/com/redhat/services/ninja/data/service/IdentifiableDatabaseOperationsImpl.java, quarkus/data-service/src/test/java/com/redhat/services/ninja/data/controller/LevelResourceTest.java, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/ErrorResponse.java, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/Level.java, quarkus/scorecard-service/src/main/java/com/redhat/services/ninja/controller/LevelResource.java, quarkus/scorecard-service/src/main/java/com/redhat/services/ninja/controller/ScorecardResource.java, quarkus/scorecard-service/src/test/java/com/redhat/services/ninja/controller/LevelResourceTest.java, quarkus/test-helper/src/main/resources/com/redhat/services/ninja/test/database.json
Level endpoint is now available.
=> Backend Quarkus Level: Adding ability to view all levels

quarkus/all-service/src/main/resources/META-INF/openapi.yaml, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/Scorecard.java, quarkus/scorecard-service/src/test/java/com/redhat/services/ninja/controller/ScorecardResourceTest.java, quarkus/test-helper/src/main/resources/com/redhat/services/ninja/test/database.json
Ensuring that Scorecard complies with open api spec.
=> Backend Quarkus Scorecard: Changing pointmap to details

.openshift/templates/jenkins-pipeline.yaml, .openshift/templates/ninja-board-back-end.yaml, .openshift/templates/ninja-board-front-end.yaml, Getting-Started.md, react/ninja-react/.openshift/templates/ninja-board-front-end.yml
Adding resource configuration for deployment in personal namespace
=> CI: Adding support for developer personal development.

openapi/openapi.yaml, quarkus/all-service/pom.xml, quarkus/all-service/src/main/resources/META-INF/openapi.yaml, quarkus/all-service/src/main/resources/application.properties, quarkus/data-client/src/main/java/com/redhat/services/ninja/client/EventClient.java, quarkus/data-service/src/test/java/com/redhat/services/ninja/data/controller/EventResourceTest.java, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/Event.java, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/Point.java, quarkus/event-service/pom.xml, quarkus/event-service/src/main/java/com/redhat/services/ninja/controller/EventResource.java, quarkus/event-service/src/test/java/com/redhat/services/ninja/controller/EventResourceTest.java, quarkus/quarkus-pom/pom.xml, quarkus/scorecard-service/src/main/java/com/redhat/services/ninja/controller/ScorecardResource.java, quarkus/scorecard-service/src/test/java/com/redhat/services/ninja/controller/ScorecardResourceTest.java, quarkus/test-helper/src/main/resources/com/redhat/services/ninja/test/database.json, quarkus/user-service/src/main/java/com/redhat/services/ninja/controller/UserResource.java, quarkus/user-service/src/test/java/com/redhat/services/ninja/controller/UserResourceTest.java
=> Backend Quarkus Event: Adding Event Service

quarkus/README.MD, quarkus/all-service/src/main/resources/application.properties, quarkus/all-service/src/main/resources/reflection-config.json, quarkus/entities/pom.xml, quarkus/entities/src/main/java/com/redhat/services/ninja/entity/Database.java, quarkus/pom.xml
Application can now be built and run natively
Signed-off-by: Adler Fleurant <2609856+AdlerFleurant@users.noreply.github.com>
=> Backend Quarkus Native: Enabling Native Build

.openshift/templates/ninja-board-build.yml, README.md
Readme is modified to be clear on the ansible deployment for v2.
Unneeded deployment resources has been removed.
Signed-off-by: Adler Fleurant <2609856+AdlerFleurant@users.noreply.github.com>
=> Pipeline: Openshift v4 Deployment

src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/java/com/redhat/sso/ninja/ManagementController.java, src/main/webapp/mojo/igloo-ninjaWall.jsp, src/main/webapp/mojo/igloo-raceToBlackBelt.jsp
- Added an event to the event log whenever a user changes any of their information
- Push the updated user info to the graphs cache to be read by the Dashboard (otherwise the user doesn't see their change until the next system run, leading to a poor user experience)
=> Self service updates

src/main/java/com/redhat/sso/ninja/ManagementController.java
Improved user editing by allowing any user details to be edited (whether they have a scorecard or not). prevously only users with scorecards could be edited in the UI (a known bug)
Also added an event for each value changed so we have a data update log over time
=> improved user editing

src/main/java/com/redhat/sso/ninja/Database2.java, src/main/java/com/redhat/sso/ninja/Heartbeat2.java, src/main/java/com/redhat/sso/ninja/PointsAllocation.java, src/main/java/com/redhat/sso/ninja/ScriptRunner.java, src/main/java/com/redhat/sso/ninja/controllers/EventsController.java, src/main/webapp/mojo/igloo-ninjaWall.jsp, src/main/webapp/mojo/mojo-dashboard-card.jsp
new script execution code - it reads the streams better so with larger trello calls it doesnt hang
fixed an event text bug where the links were not displaying correctly on the back of changing the format to separate fields
=> New script executor

.openshift/templates/ninja-board-build.yml
Update certificates within image
=> Update certificates within image

.openshift/templates/ninja-board-build.yml
=> Update python certificates
